ruby '1.9.3'
source 'https://rubygems.org'

gem 'rack'
gem 'rack-contrib'
gem 'rack-rewrite'
gem 'jekyll'
gem 'heroku'
gem 'foreman'
gem 'thin'
gem 'sass'
gem 'coffee-script'
gem 'coffee-script-source'
